# Generated by Django 5.0.6 on 2024-09-01 11:36

import tags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='tag_name',
            field=models.TextField(default='abc', verbose_name=tags.models.tags),
        ),
    ]
