# Generated by Django 5.1.1 on 2024-09-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('Farhan')
                          ""","""DELETE FROM store_collection WHERE title='Farhan'""")
    ]
